# Generated by Django 4.1.2 on 2022-10-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=64)),
                ('student_sex', models.CharField(max_length=3)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('student_id', models.IntegerField(max_length=11)),
            ],
        ),
    ]
