# Generated by Django 4.1.2 on 2022-10-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_guangzhi', '0002_course_alter_student_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_type', models.BooleanField()),
                ('score_value', models.IntegerField()),
                ('mark', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('course_id', models.IntegerField()),
            ],
        ),
    ]
